[versions]
kotlin = "2.2.21"

[libraries]

th2-common = { group = "com.exactpro.th2", name = "common", version = "5.16.1-dev" }
th2-netty-bytebuf-utils = { group = "com.exactpro.th2", name = "netty-bytebuf-utils", version = "0.3.0" }
th2-read-file-common-core = { group = "com.exactpro.th2", name = "read-file-common-core", version = "3.3.0-dev" }

opencsv = { group = "com.opencsv", name = "opencsv", version = "5.12.0" }

jakarta-annotation-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version = "3.0.0" }

junit-bom = { group = "org.junit", name = "junit-bom", version = "6.0.0" }
mockito-core = { group = "org.mockito", name = "mockito-core", version = "5.20.0" }

[plugins]
th2-component = { id = "com.exactpro.th2.gradle.component", version = "0.3.10" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }